// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/data.ts
var services = [
  {
    title: "Wedding Photography",
    description: "Capture your special day with timeless elegance. From intimate ceremonies to grand celebrations, we document every precious moment.",
    features: ["Full day coverage", "Candid & posed shots", "Album design", "Online gallery"]
  },
  {
    title: "Pre-Wedding Shoots",
    description: "Create magical memories before your big day with stunning pre-wedding photography at beautiful locations.",
    features: ["Location scouting", "Outfit consultation", "Multiple looks", "Cinematic edits"]
  },
  {
    title: "Cinematography",
    description: "Professional video production that tells your story with cinematic quality and emotional depth.",
    features: ["4K recording", "Drone footage", "Color grading", "Same-day edits"]
  },
  {
    title: "Fashion Photography",
    description: "Elevate your brand with stunning fashion photography that captures style, personality, and sophistication.",
    features: ["Studio & outdoor", "Professional styling", "Portfolio ready", "Commercial use"]
  },
  {
    title: "Drone Photography",
    description: "Capture breathtaking aerial perspectives with our professional drone photography services.",
    features: ["Licensed pilots", "High-res imagery", "Video & stills", "Event coverage"]
  },
  {
    title: "Corporate Events",
    description: "Professional coverage for conferences, product launches, and corporate gatherings.",
    features: ["Quick turnaround", "Team headshots", "Event highlights", "Brand focused"]
  }
];
var packages = [
  {
    name: "Essential",
    price: "\u20B925,000",
    description: "Perfect for intimate events and small gatherings",
    features: [
      "4 hours coverage",
      "100+ edited photos",
      "Online gallery",
      "Basic retouching",
      "1 photographer"
    ],
    popular: false
  },
  {
    name: "Premium",
    price: "\u20B950,000",
    description: "Our most popular package for weddings and events",
    features: [
      "Full day coverage",
      "300+ edited photos",
      "Online gallery + USB",
      "Advanced retouching",
      "2 photographers",
      "Pre-wedding shoot",
      "Highlight video"
    ],
    popular: true
  },
  {
    name: "Luxury",
    price: "\u20B91,00,000",
    description: "Complete coverage for your most special occasions",
    features: [
      "2-day coverage",
      "500+ edited photos",
      "Premium album",
      "Cinematic film",
      "3 photographers",
      "Pre-wedding shoot",
      "Drone coverage",
      "Same-day edit"
    ],
    popular: false
  }
];
var portfolioCategories = [
  { slug: "weddings", name: "Weddings", path: "/portfolio/weddings" },
  { slug: "portraits", name: "Portraits", path: "/portfolio/portraits" },
  { slug: "events", name: "Events", path: "/portfolio/events" },
  { slug: "commercial", name: "Commercial", path: "/portfolio/commercial" },
  { slug: "product", name: "Product", path: "/portfolio/product" },
  { slug: "fashion", name: "Fashion", path: "/portfolio/fashion" },
  { slug: "travel", name: "Travel", path: "/portfolio/travel" }
];
var contactInfo = {
  studio: "B2 Studio",
  phone: "+91 97998 87002",
  whatsapp: "https://wa.me/919799887002",
  emails: ["hello@b2studio.com", "bookings@b2studio.com"],
  address: "123 Photography Lane, Mumbai, Maharashtra 400001",
  workingHours: ["Mon - Sat: 10:00 AM - 7:00 PM", "Sunday: By Appointment"],
  social: {
    instagram: "https://instagram.com/b2studio",
    facebook: "https://facebook.com/b2studio",
    youtube: "https://youtube.com/b2studio"
  }
};
var eventTypes = [
  "Wedding",
  "Pre-Wedding",
  "Corporate Event",
  "Fashion Shoot",
  "Product Shoot",
  "Portrait Session",
  "Other"
];

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "List photography services",
  description: "List the photography and video services B2 Studio offers, with their descriptions and included features.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-packages.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_packages_default = defineTool2({
  name: "list_packages",
  title: "List pricing packages",
  description: "List B2 Studio's booking packages with prices and what each one includes.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(packages, null, 2) }],
    structuredContent: { packages }
  })
});

// src/lib/mcp/tools/list-portfolio-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_portfolio_categories_default = defineTool3({
  name: "list_portfolio_categories",
  title: "List portfolio categories",
  description: "List the portfolio galleries on the B2 Studio website and the page path for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(portfolioCategories, null, 2) }],
    structuredContent: { categories: portfolioCategories }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get studio contact info",
  description: "Get B2 Studio's public contact details: phone, WhatsApp, emails, address, working hours and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contactInfo, null, 2) }],
    structuredContent: { contact: contactInfo }
  })
});

// src/lib/mcp/tools/submit-inquiry.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/submit-inquiry.ts
var submit_inquiry_default = defineTool5({
  name: "submit_inquiry",
  title: "Submit a booking inquiry",
  description: "Send a booking inquiry to B2 Studio, exactly like the website's public contact form. Inquiries cannot be read back.",
  inputSchema: {
    full_name: z.string().trim().min(1).describe("Name of the person inquiring."),
    email: z.string().trim().email().describe("Contact email address."),
    phone: z.string().trim().min(1).optional().describe("Optional contact phone number."),
    event_type: z.string().trim().min(1).describe(`Type of shoot or event. Common values: ${eventTypes.join(", ")}.`),
    preferred_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Optional preferred date in YYYY-MM-DD format."),
    message: z.string().trim().min(1).describe("Details about the shoot or event.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input) => {
    const supabase = supabaseAnon();
    const { error } = await supabase.from("inquiries").insert([
      {
        full_name: input.full_name,
        email: input.email,
        phone: input.phone ?? null,
        event_type: input.event_type,
        preferred_date: input.preferred_date ?? null,
        message: input.message
      }
    ]);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: "Inquiry submitted. The B2 Studio team will get back to you shortly."
        }
      ],
      structuredContent: { submitted: true }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "b2-studio-moments",
  title: "b2-studio-moments",
  version: "0.1.0",
  instructions: "Tools for B2 Studio, a photography and cinematography studio. Use `list_services` and `list_packages` for offerings and pricing, `list_portfolio_categories` for galleries, `get_contact_info` for contact details, and `submit_inquiry` to send a booking request.",
  tools: [
    list_services_default,
    list_packages_default,
    list_portfolio_categories_default,
    get_contact_info_default,
    submit_inquiry_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
